### ISSUE TITLE
#bug "Seçim Sonuçları" kısmındaki hata

### ISSUE THREAD

**Issue by MisakiTaro15** [SaydikBiz/reports#1]
"Seçim Sonuçları" kısmı herhalde test için yapılmış. Oranın kaldırılması gerekiyor, sonrasında "DEVA'nın platformu yalan anket paylaşıyor" tarzı bir haber olmasın, teşekkürler.

**Comment by isayeter** [comment]
Merhabalar, şu an sistem seçim gününe kadar test aşamasındadır, ve ekranlarda yüklenen test tutanaklarının sonuçları yazmaktadır, tabii ki seçimden önce bütün veritabanı sıfırlanacak. Teşekkürler.
