### ISSUE TITLE
#enhancement

### ISSUE THREAD

**Issue by KadirCT** [SaydikBiz/reports#12]
Sahiplenilen sandıkların yanına kaç kişi tarafından sahiplenildiği yazılırsa ve sıralama en az sahiplenilenden en çok sahiplenilene doğru yapılırsa insanlar az sahiplenilen yerleri seçebilir. Mesela benim kısa sürede yürüyerek dahi gidebileceğim 10-15 okul var. Ben hangisinin daha az sahiplenildiğini bilmeden rastgele birini seçtim. İvedilikle böyle bir güncelleme getirilmesini talep ediyorum. Getirildiği takdirde yüzlerce kişiyi sadece ben bile sandıklara yönlendirebilirim :)

İyi çalışmalar ❤

**Comment by isayeter** [comment]
yapildi, yayinda, tesekkurler 🙏
