### ISSUE TITLE
Açık Kaynak

### ISSUE THREAD

**Issue by Bturan19** [SaydikBiz/reports#13]
Merhaba, uygulamayı açık kaynak haline getirmek mümkün müdür? Güzel bir çalışma olmuş ama sadece belirli bir kullanıcı kitlesi ile sınırlı kalmış. Siteye raporlama ile ilgili eklemeler yapabiliriz ve daha yaygın kullanımına destek olabiliriz..

**Comment by isayeter** [comment]
Maalesef bu pek mümkün değil, hem security açısından da olmamalı bu.
