### ISSUE TITLE
#bug Masaüstü Menü Hatası

### ISSUE THREAD

**Issue by Sartman34** [SaydikBiz/reports#2]

**Comment by Sartman34** [comment]
masaüstünden web sitesine girildiğinde soldaki menü scrollanamıyor.
bu github linkine telefondan ulaşabildim.

**Comment by isayeter** [comment]
Bilgilendirme için teşekkürler, bug fixlenene kadar issue açık kalabilir.

**Comment by isayeter** [comment]
elimizdeki TODO'lardan dolayı, bu konu hakkında destek beklemekteyiz, bug fix yapabilecek varsa lütfen fixlemem gereken kısmı buradan paylaşabilir mi. Teşekkürler

**Comment by SwitchAlpha** [comment]
> masaüstünden web sitesine girildiğinde soldaki menü scrollanamıyor. bu github linkine telefondan ulaşabildim.

Ekran çözünürlüğün nedir hatayı kendimde oluşturmayı deneyeceğim

**Comment by isayeter** [comment]
browser'da developer console açılıp, sol üstteki telefon ikonuna basıp ekran boyutunu istedigin gibi resize edebilirsin, height'ı 320px vs denenebilir.

**Comment by SwitchAlpha** [comment]
> browser'da developer console açılıp, sol üstteki telefon ikonuna basıp ekran boyutunu istedigin gibi resize edebilirsin, height'ı 320px vs denenebilir.

Arkadaş telefonda sıkıntı olmadığını bilgisayarda olduğunu söylemiş

**Comment by isayeter** [comment]
> > browser'da developer console açılıp, sol üstteki telefon ikonuna basıp ekran boyutunu istedigin gibi resize edebilirsin, height'ı 320px vs denenebilir.
> 
> Arkadaş telefonda sıkıntı olmadığını bilgisayarda olduğunu söylemiş

ben de zaten masaüstü browser'da yapman gerekeni yazdım.

**Comment by berkayylmao** [comment]
CSS koduna aşağıdakilere eklerseniz sorun çözülmekte:

```css
.multinav {
  max-height: 100%;
  overflow-y: scroll;
}
```

**Comment by isayeter** [comment]
Bu sorun hâlâ devam ediyor mu? Sanki zaten bir ara fixlemişim gibi şu an test yaptığımda sorunla karşılaşmadım

**Comment by isayeter** [comment]
evet devam ediyormuş, @berkayylmao çok teşekkür ederim fix için 🙏, siteye commitledim live'de şu an.

**Comment by berkayylmao** [comment]
Ek olarak yukarı verdiğim CSS'i `@media (max-height: 800px) {}` içerisine alırsanız gerekmediğinde scrollbar gözükmez:

```css
.mainbar {
  // ...
}

@media (max-height: 800px) {
  .multinav {
    max-height: 100%;
    overflow-y: scroll;
  }
}
```

`overflow`u `auto`ya ayarlayınca bazı tarayıcılar maalesef `scroll` eylemine geçiş yapmıyor, o yüzden sorunun etrafından dolaşmak gerekebiliyor:(

**Comment by isayeter** [comment]
@berkayylmao bu da canlı ya alındı, çok teşekkürler
