### ISSUE TITLE
#bug ok asagi donmuyor

### ISSUE THREAD

**Issue by knkemree** [SaydikBiz/reports#3]
Herhangi bir ilceyi tikliyorum ok saga dogru gostermesi lazim. expand olunca asagi donmesi lazim. fakat oklar hep asagi donuk. kafa karisikligina sebebiyet veriyor. hangi ilcenin expand edildigi anlasilmiyor.
![image](https://user-images.githubusercontent.com/48003537/226501480-9afb4638-93ea-4920-ad6b-6ee9af79037f.png)

Bir de her hangi bir sehri tikladiktan sonra zoom in yapiyor ama tek tikla genel turkiye haritasina donme secenegi yok. illa zoom out yapmak gerekiyor.

**Comment by isayeter** [comment]
Merhaba, öneriler için teşekkürler, "ok" konusuna güncelleme geçeceğim, 
Bir şehire tıkladıktan sonra, aynı şehire tekrar tıklayınca genel haritaya tekrar dönüyor, dediğiniz gibi filtreleri kaldırma butonu eklenebilir, 
Teşekkürler.
