### ISSUE TITLE
#bug oy almayanlarin 0 olarak girilmesi gerektigi

### ISSUE THREAD

**Issue by knkemree** [SaydikBiz/reports#5]
tutanaka verileri girilirken oy almayanlarin mutlaka 0 girilmesi gerektigi anlasilmiyor. fill this blank yaziyor ama bence partinin oyu yoksa 0 girilmelidir diye daha acik bir mesaj dondurulmeli.

**Comment by isayeter** [comment]
Evet, bu kısım en kısa sürede güncellenecek, şimdilik açık bırakıyorum bu issue'yu, Teşekkürler.

**Comment by isayeter** [comment]
bu fixlendi, 0 oy girilebiliyor artık. teşekkürler.
