### ISSUE TITLE
#enhancement Profil bilgilerinin düzenlenememesi

### ISSUE THREAD

**Issue by efkandurakli** [SaydikBiz/reports#6]
Profil bilgilerinin güncellenebilir olması lazım. Ben ilk kayıt oluştururken sandık görevlisi olup olmayacağım belli olmadığı için sandık görevlisi olarak giriş yapmadım. Sandık görevlisi olursam, profilime bunu nasıl ekleyeceğim?

**Comment by isayeter** [comment]
Merhaba, vatandaş olarak giriş yaptığınız için ekstra bir şey yapmanıza gerek yok, "sandık görevlisi girişi" kısmı parti üyeleri için hazırlanmış olup daha sonra aktifleştirilecektir. Teşekkürler.
