### ISSUE TITLE
#bug sahiplenilen sandik orani

### ISSUE THREAD

**Issue by knkemree** [SaydikBiz/reports#7]
Dun sahiplenilen sandik sayisi 48336'ydi yuzdesi 3,36'ydi. Suan sahiplenilen sandik sayisini hala 48336 olarak gosteriyor fakat oran yuzde 4,08. Bir yerlerde bir hata mi var? bir de dun total sandik sayisini da gosteriyordu. suan gostermiyor.
![image](https://user-images.githubusercontent.com/48003537/226702962-6e88402a-8dd6-4ee0-b343-80ea72b65c93.png)

**Comment by isayeter** [comment]
Merhaba, "48336" rakamı sahiplenilen sandık sayısı değil, toplam hedeflenen mahalle sayısıdır. Yüzde oranı ile bu rakamı çarptığımızda, sahiplenilen mahalle sayısına ulaşabilirsiniz. Teşekkürler.
