### ISSUE TITLE
#question DDoS Saldırıları İçin Önlem

### ISSUE THREAD

**Issue by Sartman34** [SaydikBiz/reports#8]
Olası DDoS saldırılarını engellemek için bir korumanız, planınız var mı? Malesef bireysel web sitesi ve sunucular bile büyük DDoS saldırılarına maruz kalabiliyor.

**Comment by canarslan12** [comment]
siteyi biraz inceledim, DDoS için cloudflare ve belli miktarda amazon servisleri kullanılıyor. Bu güzel bir gelişme ancak yeterli değil. Service Worker ile birlikte site doğrudan bağlantı yokken bile kullanılabilir hale getirilmeli, gerekirse farklı ip ler üzerinden erişimin devamlılığı sw aracılığı ile sağlanmalı çünkü site adresi btk tarafından yasaklanılabilir, çeşitli ip adresleriniz bloklanabilir, veri merkezinin interneti kesilebilir. sistemler yedekli olmalı. 
YSK sistemi ile de doğrudan bağlantılı bir yapı var, YSK ile paylaşılan IP adresleri de doğrudan ddos saldırısı alabilir, bunların da sistedeki diğer IP adreslerinden/sunuculardan farklı olması gerekiyor.

**Comment by knkemree** [comment]
deva secimlere girmedigi icin ysk, devaya secsis sistemine erisime izin vermiyordur. muhtemelen ysk ile paylasilan ip'ler chp'ye veya  iyi partiye aittir. bugun chp'den sistemlerimizi yurrtdisi erisimine kapattik diye bir aciklama geldi fakat dediginiz gibi btk tarafindan bu ip adresleri de bloklanabilir. bu da saydik.biz'in ysk entegrasyonuna direk balta vurmus olur. sitedeki versiyon tanitimlarindan anladigim kadariyla ysk entegrasyonu secsis'e girilen hatali bir sonuc var mi diye kullanilacak.

**Comment by canarslan12** [comment]
Evet, YSK dan veri çekmek pazartesi öğlene kadar pek anlamlı değil, YSK bütün partiler ile paylaşıyor verileri bildiğim kadarıyla. 
Bahsettiğim YSK nın ip adresini bloklaması değil elindeki ip adresinin DDOS saldırısı yapılması için dışarı sızdırılma riskiydi

**Comment by haliliceylan** [comment]
En basitinden resim yükleme kısımlarında yoksa captcha eklenebilir
